#!/usr/bin/env groovy

pipeline {
	agent {
		docker { image 'xtensa-esp32-build' }
	}
	stages {
		stage('Fetch') {
			steps {
				sh 'rm -rf amazon-freertos'
				sh 'git clone https://github.com/aws/amazon-freertos'
			}
		}
		stage('Build') {
			steps {
				dir('amazon-freertos/demos/espressif/esp32_devkitc_esp_wrover_kit/make') {
					sh 'cov-build --dir idir --emit-complementary-info make'
					sh 'cov-analyze --dir idir --all --strip-path `pwd`'
				}
			}
		}
		stage('Test') {
			steps {
				sh 'echo No tests.'
			}
		}
	}
}
